export let products = [
  { id: 1, title: "The Alchemist", author: "Paulo Coelho", price: 399 },
  { id: 2, title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", price: 499 },
  { id: 3, title: "Atomic Habits", author: "James Clear", price: 450 },
  { id: 4, title: "The Power of Your Subconscious Mind", author: "Joseph Murphy", price: 299 },
  { id: 5, title: "Ikigai", author: "Héctor García", price: 350 },
  { id: 6, title: "The Psychology of Money", author: "Morgan Housel", price: 500 },
  { id: 7, title: "Think and Grow Rich", author: "Napoleon Hill", price: 550 },
  { id: 8, title: "Deep Work", author: "Cal Newport", price: 420 },
  { id: 9, title: "The Monk Who Sold His Ferrari", author: "Robin Sharma", price: 480 },
  { id: 10, title: "Can't Hurt Me", author: "David Goggins", price: 600 },
  { id: 11, title: "Start With Why", author: "Simon Sinek", price: 530 },
  { id: 12, title: "Zero to One", author: "Peter Thiel", price: 499 },
  { id: 13, title: "The Lean Startup", author: "Eric Ries", price: 550 },
  { id: 14, title: "Rework", author: "Jason Fried", price: 470 },
  { id: 15, title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", price: 420 },
  { id: 16, title: "You Can Win", author: "Shiv Khera", price: 490 },
  { id: 17, title: "The Secret", author: "Rhonda Byrne", price: 530 },
  { id: 18, title: "Sapiens", author: "Yuval Noah Harari", price: 700 },
  { id: 19, title: "Homo Deus", author: "Yuval Noah Harari", price: 750 },
  { id: 20, title: "21 Lessons for the 21st Century", author: "Yuval Noah Harari", price: 680 },
  { id: 21, title: "The 5 AM Club", author: "Robin Sharma", price: 620 },
  { id: 22, title: "The Magic of Thinking Big", author: "David J. Schwartz", price: 540 },
  { id: 23, title: "Tools of Titans", author: "Tim Ferriss", price: 800 },
  { id: 24, title: "The 4-Hour Workweek", author: "Tim Ferriss", price: 750 },
  { id: 25, title: "Grit", author: "Angela Duckworth", price: 600 },
  { id: 26, title: "Mindset", author: "Carol S. Dweck", price: 590 },
  { id: 27, title: "Dare to Lead", author: "Brené Brown", price: 650 },
  { id: 28, title: "How to Win Friends and Influence People", author: "Dale Carnegie", price: 580 },
  { id: 29, title: "The Art of War", author: "Sun Tzu", price: 500 },
  { id: 30, title: "The One Thing", author: "Gary Keller", price: 570 },
  { id: 31, title: "The 10X Rule", author: "Grant Cardone", price: 690 },
  { id: 32, title: "Purple Cow", author: "Seth Godin", price: 520 },
  { id: 33, title: "Hooked", author: "Nir Eyal", price: 550 },
  { id: 34, title: "Made to Stick", author: "Chip Heath & Dan Heath", price: 600 },
  { id: 35, title: "The Hard Thing About Hard Things", author: "Ben Horowitz", price: 680 },
  { id: 36, title: "Measure What Matters", author: "John Doerr", price: 640 },
  { id: 37, title: "The Ride of a Lifetime", author: "Robert Iger", price: 590 },
  { id: 38, title: "Shoe Dog", author: "Phil Knight", price: 720 },
  { id: 39, title: "Good to Great", author: "Jim Collins", price: 750 },
  { id: 40, title: "The Innovator's Dilemma", author: "Clayton Christensen", price: 700 },
  { id: 41, title: "Blue Ocean Strategy", author: "W. Chan Kim", price: 670 },
  { id: 42, title: "The Design of Everyday Things", author: "Don Norman", price: 650 },
  { id: 43, title: "The Elements of User Experience", author: "Jesse James Garrett", price: 590 },
  { id: 44, title: "Steal Like an Artist", author: "Austin Kleon", price: 450 },
  { id: 45, title: "Show Your Work!", author: "Austin Kleon", price: 480 },
  { id: 46, title: "The War of Art", author: "Steven Pressfield", price: 530 },
  { id: 47, title: "So Good They Can't Ignore You", author: "Cal Newport", price: 510 },
  { id: 48, title: "Drive", author: "Daniel H. Pink", price: 550 },
  { id: 49, title: "The Dip", author: "Seth Godin", price: 460 },
  { id: 50, title: "Linchpin", author: "Seth Godin", price: 580 },
  { id: 51, title: "The Everything Store", author: "Brad Stone", price: 600 },
  { id: 52, title: "The Bezos Letters", author: "Steve Anderson", price: 620 },
  { id: 53, title: "The Lean UX", author: "Jeff Gothelf", price: 540 },
  { id: 54, title: "Deep Learning", author: "Ian Goodfellow", price: 950 },
  { id: 55, title: "Artificial Intelligence", author: "Stuart Russell", price: 890 },
  { id: 56, title: "The Algorithm Design Manual", author: "Steven S. Skiena", price: 990 },
  { id: 57, title: "Designing Data-Intensive Applications", author: "Martin Kleppmann", price: 1050 },
  { id: 58, title: "Computer Networking", author: "James F. Kurose", price: 880 },
  { id: 59, title: "Cracking the Coding Interview", author: "Gayle Laakmann McDowell", price: 750 },
  { id: 60, title: "Eloquent JavaScript", author: "Marijn Haverbeke", price: 500 },
  // ✅ Limited editions
  { id: 61, title: "Sherlock Holmes - Collector's Edition", author: "Arthur Conan Doyle", price: 1299, limitedEdition: true },
  { id: 62, title: "Harry Potter - 20th Anniversary Edition", author: "J.K. Rowling", price: 1999, limitedEdition: true },
  { id: 63, title: "The Hobbit - Illustrated Edition", author: "J.R.R. Tolkien", price: 1599, limitedEdition: true },
  { id: 64, title: "Game of Thrones - Leather Bound Set", author: "George R.R. Martin", price: 2999, limitedEdition: true },
  { id: 65, title: "Lord of the Rings - Gold Embossed Edition", author: "J.R.R. Tolkien", price: 2499, limitedEdition: true },
  { id: 66, title: "Steve Jobs - Special Edition", author: "Walter Isaacson", price: 1799, limitedEdition: true },
  { id: 67, title: "Leonardo da Vinci - Deluxe Edition", author: "Walter Isaacson", price: 1999, limitedEdition: true },
  { id: 68, title: "The Great Gatsby - Leather Bound", author: "F. Scott Fitzgerald", price: 999, limitedEdition: true },
  { id: 69, title: "Pride and Prejudice - Collector’s Edition", author: "Jane Austen", price: 1099, limitedEdition: true },
  { id: 70, title: "To Kill a Mockingbird - Limited Run", author: "Harper Lee", price: 1199, limitedEdition: true },
  // ✅ Game Director Story Books (Hot Sale)
  { id: 71, title: "Hideo Kojima: The Creative Gene", author: "Hideo Kojima", price: 1299, hotSale: true },
  { id: 72, title: "Sid Meier’s Memoir!", author: "Sid Meier", price: 1099, hotSale: true },
  { id: 73, title: "The Art of Naughty Dog", author: "Naughty Dog Studios", price: 1499, hotSale: true },
  { id: 74, title: "Miyamoto: The Man Behind Mario", author: "Jeff Ryan", price: 1399, hotSale: true },
  { id: 75, title: "John Romero: Doom Guy", author: "John Romero", price: 1599, hotSale: true },
  { id: 76, title: "Carmack & Romero: The Masters of FPS", author: "David Kushner", price: 1699, hotSale: true },
  { id: 77, title: "Ken Levine: The Mind Behind Bioshock", author: "Geoff Keighley", price: 1499, hotSale: true },
  { id: 78, title: "The Making of Final Fantasy", author: "Yoshitaka Amano", price: 1799, hotSale: true },
  { id: 79, title: "The Legend of Zelda: Creating a Classic", author: "Nintendo", price: 1999, hotSale: true },
  { id: 80, title: "The Last of Us: Official Art & Story", author: "Neil Druckmann", price: 1899, hotSale: true }
];
